version: '3.4'

services:
  postman:
    image: web-scanner-k6
    container_name: web-scanner-k6
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: Local
      